version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    # image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    network_mode: bridge
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-1}
      - SERVICES=ssm,s3,lambda,cloudformation,iam,apigateway,logs,acm,secretsmanager,sts,route53
      - AWS_DEFAULT_REGION=us-east-2
      - DEFAULT_REGION=us-east-2
      - LOCALSTACK_AUTH_TOKEN=ls-MEBipISi-0002-PAre-YAPA-3428ZOfu3012
      - LOCALSTACK_ENV=true
      - PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"